#define inti 1
#define booli 2
#define stringi 3
#define arrayi 4
#define floati 5
#define plusi 6
#define minusi 7
#define multiplication 8
#define div 9
#define floatdiv 10
#define mod 11
#define less 12
#define great 13
#define lessequal 14
#define greatequal 15
#define equal 16
#define not 17
#define notequal 18
#define readi 19
#define writei 20
#define ifi 21
#define elsei 22
#define fori 23
#define whilei 24
#define doi 25
#define openacc 26
#define closeacc 27
#define openpara 28
#define closepara 29
#define semicolon 30
#define comma 31
#define and 32
#define or 33
#define attribution 34
#define id 35
#define cnst 36
